# Generated by Django 2.0.5 on 2018-05-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
