# Generated by Django 2.0.5 on 2018-05-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_itemdetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
