# Generated by Django 2.0.5 on 2018-05-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180516_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetail',
            name='description',
        ),
        migrations.AddField(
            model_name='listitem',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
