# Generated by Django 2.0.5 on 2018-05-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamuser',
            name='user_permission',
            field=models.CharField(choices=[('0', 'general_user'), ('1', 'administrator'), ('2', 'super_administrator')], default='0', max_length=2),
        ),
    ]
