# Generated by Django 2.0.5 on 2018-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_teamuser_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_team',
            field=models.IntegerField(null=True),
        ),
    ]
